### ISSUE TITLE
Update to newer version of Lunr

### ISSUE THREAD

**Issue by Trolleymusic** [Wiredcraft/lunr-chinese#2]
Hello, do you have any plans to update this to a newer version of Lunr?

**Comment by ole3021** [comment]
@Trolleymusic Not for now, the reason is the most changes of `Lunr` v2 is about the tokenize method, which improves the performance for English, but it does not work for Chinese. So for Chinese the Lunr v0.7.2 is the most suitable version.

**Comment by ole3021** [comment]
I updated the reason in README, and please let me know if you have found any bugs that during use `lunr-chinese`, and I will try to fix it.
